exports.sampleProducts = [
    {
      name: "Fresh Milk",
      description: "High-quality fresh milk from local farms",
      price: 2.5,
      category: "Dairy",
      Stock: 50,
    },
    {
      name: "Whole Wheat Bread",
      description: "Nutritious whole wheat bread for a healthy diet",
      price: 1.5,
      category: "Bakery",
      Stock: 100,
    },
    {
      name: "Organic Eggs",
      description: "Farm-fresh organic eggs rich in nutrients",
      price: 3.0,
      category: "Dairy",
      Stock: 30,
    },
    {
      name: "Fresh Apples",
      description: "Crispy and juicy apples for a delicious snack",
      price: 2.0,
      category: "Fruits",
      Stock: 40,
    },
    {
      name: "Brown Rice",
      description: "High-fiber brown rice for a wholesome meal",
      price: 2.8,
      category: "Grains",
      Stock: 60,
    },
    {
      name: "Chicken Breast",
      description: "Lean chicken breast for a protein-packed meal",
      price: 5.0,
      category: "Meat",
      Stock: 20,
    },
    {
      name: "Fresh Spinach",
      description: "Nutrient-rich fresh spinach for salads and cooking",
      price: 1.8,
      category: "Vegetables",
      Stock: 25,
    },
    {
      name: "Orange Juice",
      description: "Refreshing orange juice for a healthy beverage",
      price: 3.5,
      category: "Beverages",
      Stock: 45,
    },
    {
      name: "Tomato Sauce",
      description: "Homemade tomato sauce for pasta and recipes",
      price: 2.2,
      category: "Canned Goods",
      Stock: 35,
    },
    {
      name: "Dark Chocolate",
      description: "Premium dark chocolate for sweet indulgence",
      price: 4.0,
      category: "Sweets",
      Stock: 15,
    },
  ];
  
  exports.sampleUsers = [
    {
      name: "Swaroop",
      email:'nswaroop1999@gmail.com',
      password:'!Swarooptest',
      role:'admin',
    },
    {
      name: "Akhil",
      email:'akhil@gmail.com',
      password:'!Akhiltest',
    },
  ];

  exports.Productsdata =[{"category":"Health Supplies","name":"Cotton_balls"},
  {"category":"Dairy","name":"Whipped_Cream"},
  {"category":"Beverages","name":"Tea"},
  {"category":"Sweets","name":"Hersheys_Milk_Chocolate"},
  {"category":"Frozen","name":"Frozen_Organic_spinach"},
  {"category":"Spices","name":"Fenugreek"},
  {"category":"Beverages","name":"Spring_Water"},
  {"category":"Dairy","name":"Cheese"},
  {"category":"Canned Goods","name":"Organic_Canned_Coconut_milk"},
  {"category":"Health Supplies","name":"First_aid_tape"},
  {"category":"Grains and Lentils","name":"Couscous"},
  {"category":"Produce","name":"Organic_Orange"},
  {"category":"Frozen","name":"Frozen_berries"},
  {"category":"Health Supplies","name":"Insect_repellent"},
  {"category":"Spices","name":"Dill"},
  {"category":"Frozen","name":"Frozen_pasta"},
  {"category":"Baby Care","name":"Teething_toys"},
  {"category":"Condiments","name":"Ranch_Dressing"},
  {"category":"Office Supplies","name":"Pencil"},
  {"category":"Meat","name":"Shrimp"},
  {"category":"Grains and Lentils","name":"Oats"},
  {"category":"Spices","name":"Thyme"},
  {"category":"Sweets","name":"Ferrero_Rocher"},
  {"category":"Condiments","name":"Miso_Paste"},
  {"category":"Sweets","name":"Baby_Ruth"},
  {"category":"Canned Goods","name":"Canned_Tomatoes"},
  {"category":"Frozen","name":"Frozen_garlic_bread"},
  {"category":"Sweets","name":"Jolly_Rancher"},
  {"category":"Grains and Lentils","name":"Organic_Amaranth"},
  {"category":"Grains and Lentils","name":"Millet"},
  {"category":"Flour","name":"All-Purpose_Flour"},
  {"category":"Office Supplies","name":"Mouse_Pad"},
  {"category":"Dairy","name":"Condensed_Milk"},
  {"category":"Dairy","name":"Organic_Evaporated_Milk"},
  {"category":"Flour","name":"Cornmeal"},
  {"category":"Dairy","name":"Cottage_Cheese"},
  {"category":"Oils","name":"Organic_Palm_Oil"},
  {"category":"Produce","name":"Organic_Bell_Pepper"},
  {"category":"Frozen","name":"Frozen_Organic_corn"},
  {"category":"Oils","name":"Macadamia_Nut_Oil"},
  {"category":"Canned Goods","name":"Organic_Canned_Beans"},
  {"category":"Beverages","name":"Coca-Cola"},
  {"category":"Canned Goods","name":"Organic_Canned_Spaghetti_sauce"},
  {"category":"Office Supplies","name":"Tracing_paper"},
  {"category":"Office Supplies","name":"Paper_napkins"},
  {"category":"Oils","name":"Coconut_Oil"},
  {"category":"Office Supplies","name":"Construction_paper"},
  {"category":"Office Supplies","name":"Sharpener"},
  {"category":"Frozen","name":"Frozen_Organic_pizza"},
  {"category":"Baby Care","name":"Baby_lotion"},
  {"category":"Canned Goods","name":"Organic_Canned_Chicken_broth"},
  {"category":"Dairy","name":"Organic_Cheddar_Cheese"},
  {"category":"Grains and Lentils","name":"Organic_Kidney_Beans"},
  {"category":"Oils","name":"Organic_Corn_Oil"},
  {"category":"Condiments","name":"Sriracha"},
  {"category":"Baby Care","name":"Baby_swaddle_blankets"},
  {"category":"Frozen","name":"Frozen_peas"},
  {"category":"Canned Goods","name":"Canned_Chickpeas"},
  {"category":"Spices","name":"Coriander"},
  {"category":"Bath","name":"Essential_Oils"},
  {"category":"Grains and Lentils","name":"Organic_Couscous"},
  {"category":"Bath","name":"Loofah"},
  {"category":"Oils","name":"Organic_Peanut_Oil"},
  {"category":"Dairy","name":"Organic_Butter"},
  {"category":"Beverages","name":"Hot_Chocolate_Mix"},
  {"category":"Sweets","name":"Twix"},
  {"category":"Oils","name":"Almond_Oil"},
  {"category":"Condiments","name":"Pesto"},
  {"category":"Produce","name":"Organic_Cucumber"},
  {"category":"Flour","name":"Whole_Wheat_Flour"},
  {"category":"Office Supplies","name":"Index_Cards"},
  {"category":"Beverages","name":"Coffee_Beans"},
  {"category":"Health Supplies","name":"First_aid_manual"},
  {"category":"Bath","name":"Bath_Towel"},
  {"category":"Baby Care","name":"Baby_lotion_with_chamomile"},
  {"category":"Dairy","name":"Organic_Yogurt"},
  {"category":"Office Supplies","name":"Ruler"},
  {"category":"Dairy","name":"Mozzarella_Cheese"},
  {"category":"Produce","name":"Organic_Avocado"},
  {"category":"Dairy","name":"Butter"},
  {"category":"Frozen","name":"Frozen_Organic_chicken_breasts"},
  {"category":"Produce","name":"Mushroom"},
  {"category":"Grains and Lentils","name":"Black-eyed_Peas"},
  {"category":"Meat","name":"Fish"},
  {"category":"Condiments","name":"Worcestershire_Sauce"},
  {"category":"Office Supplies","name":"Tissue_paper"},
  {"category":"Grains and Lentils","name":"Organic_Black-eyed_Peas"},
  {"category":"Sweets","name":"Peppermint_Pattie"},
  {"category":"Bath","name":"Exfoliating_Scrub"},
  {"category":"Flour","name":"Almond_Flour"},
  {"category":"Canned Goods","name":"Organic_Canned_Corn"},
  {"category":"Condiments","name":"Guacamole"},
  {"category":"Spices","name":"Parsley"},
  {"category":"Bath","name":"Candles"},
  {"category":"Canned Goods","name":"Canned_Corn"},
  {"category":"Office Supplies","name":"Tape_Dispenser"},
  {"category":"Sweets","name":"M&Ms"},
  {"category":"Produce","name":"Organic_Broccoli"},
  {"category":"Oils","name":"Organic_Pumpkin_Seed_Oil"},
  {"category":"Bath","name":"Bath_Pillow"},
  {"category":"Oils","name":"Organic_Grapeseed_Oil"},
  {"category":"Office Supplies","name":"Correction_Tape"},
  {"category":"Sweets","name":"Toblerone"},
  {"category":"Sweets","name":"Maltesers"},
  {"category":"Bath","name":"Bathrobe"},
  {"category":"Office Supplies","name":"Highlighter"},
  {"category":"Dairy","name":"Yogurt"},
  {"category":"Frozen","name":"Frozen_shrimp"},
  {"category":"Produce","name":"Organic_Carrot"},
  {"category":"Condiments","name":"Mayonnaise"},
  {"category":"Health Supplies","name":"Sunscreen"},
  {"category":"Produce","name":"Organic_Apple"},
  {"category":"Spices","name":"Allspice"},
  {"category":"Office Supplies","name":"Post-it_Notes"},
  {"category":"Office Supplies","name":"Post-it_pads"},
  {"category":"Flour","name":"Semolina_Flour"},
  {"category":"Spices","name":"Cloves"},
  {"category":"Baby Care","name":"Baby_wash"},
  {"category":"Grains and Lentils","name":"Quinoa"},
  {"category":"Health Supplies","name":"Band-Aids"},
  {"category":"Office Supplies","name":"Crayon_paper"},
  {"category":"Produce","name":"Organic_Spinach"},
  {"category":"Oils","name":"Organic_Safflower_Oil"},
  {"category":"Oils","name":"Organic_Soybean_Oil"},
  {"category":"Meat","name":"Chicken"},
  {"category":"Frozen","name":"Frozen_chicken_breasts"},
  {"category":"Spices","name":"Cayenne_pepper"},
  {"category":"Health Supplies","name":"Disposable_gloves"},
  {"category":"Condiments","name":"Barbecue_Sauce"},
  {"category":"Office Supplies","name":"Wrapping_paper"},
  {"category":"Office Supplies","name":"Eraser"},
  {"category":"Canned Goods","name":"Organic_Canned_Pineapple"},
  {"category":"Produce","name":"Organic_Lettuce"},
  {"category":"Health Supplies","name":"Hand_sanitizer"},
  {"category":"Office Supplies","name":"Spiral_Bound_Notepad"},
  {"category":"Meat","name":"Turkey"},
  {"category":"Dairy","name":"Organic_Ice_Cream"},
  {"category":"Flour","name":"Quinoa_Flour"},
  {"category":"Sweets","name":"Ghirardelli_Chocolate"},
  {"category":"Meat","name":"Pork"},
  {"category":"Sweets","name":"Hersheys_Cookies_n_Creme"},
  {"category":"Baby Care","name":"Baby_hats"},
  {"category":"Flour","name":"Oat_Flour"},
  {"category":"Produce","name":"Onion"},
  {"category":"Frozen","name":"Frozen_corn"},
  {"category":"Office Supplies","name":"Magazines"},
  {"category":"Beverages","name":"Cola"},
  {"category":"Produce","name":"Potato"},
  {"category":"Canned Goods","name":"Organic_Canned_Tomatoes"},
  {"category":"Condiments","name":"Sweet_Chili_Sauce"},
  {"category":"Spices","name":"Chili_powder"},
  {"category":"Sweets","name":"Whoppers"},
  {"category":"Produce","name":"Organic_Mushroom"},
  {"category":"Beverages","name":"Beer"},
  {"category":"Sweets","name":"Starburst"},
  {"category":"Bath","name":"Bath_Tray"},
  {"category":"Condiments","name":"Hot_Sauce"},
  {"category":"Office Supplies","name":"Origami_paper"},
  {"category":"Dairy","name":"Milk"},
  {"category":"Sweets","name":"Butterfinger"},
  {"category":"Frozen","name":"Frozen_fish_fillets"},
  {"category":"Grains and Lentils","name":"Organic_Wild_Rice"},
  {"category":"Health Supplies","name":"Digital_blood_pressure_monitor"},
  {"category":"Health Supplies","name":"Antibacterial_ointment"},
  {"category":"Frozen","name":"Frozen_Organic_fish_fillets"},
  {"category":"Oils","name":"Organic_Avocado_Oil"},
  {"category":"Produce","name":"Blueberry"},
  {"category":"Sweets","name":"Smarties"},
  {"category":"Bath","name":"Foot_Scrub"},
  {"category":"Meat","name":"Venison"},
  {"category":"Dairy","name":"Organic_Cream_Cheese"},
  {"category":"Health Supplies","name":"Scissors"},
  {"category":"Condiments","name":"Tartar_Sauce"},
  {"category":"Produce","name":"Tomato"},
  {"category":"Frozen","name":"Frozen_Organic_berries"},
  {"category":"Produce","name":"Strawberry"},
  {"category":"Condiments","name":"Mustard"},
  {"category":"Baby Care","name":"Baby_wipes"},
  {"category":"Frozen","name":"Frozen_Organic_fruit"},
  {"category":"Grains and Lentils","name":"Split_Peas"},
  {"category":"Beverages","name":"Wine"},
  {"category":"Frozen","name":"Frozen_dumplings"},
  {"category":"Spices","name":"Tarragon"},
  {"category":"Office Supplies","name":"Desk_Lamp"},
  {"category":"Frozen","name":"Frozen_Organic_peas"},
  {"category":"Meat","name":"Beef"},
  {"category":"Office Supplies","name":"Legal_Pads"},
  {"category":"Canned Goods","name":"Canned_Black_olives"},
  {"category":"Canned Goods","name":"Canned_Chicken_broth"},
  {"category":"Oils","name":"Organic_Sesame_Oil"},
  {"category":"Bath","name":"Bath_Bombs"},
  {"category":"Office Supplies","name":"Calculator"},
  {"category":"Produce","name":"Avocado"},
  {"category":"Health Supplies","name":"Nasal_saline_spray"},
  {"category":"Office Supplies","name":"Paper_bags"},
  {"category":"Grains and Lentils","name":"Organic_Barley"},
  {"category":"Bath","name":"Hand_Towel"},
  {"category":"Spices","name":"Bay_leaves"},
  {"category":"Office Supplies","name":"Stapler"},
  {"category":"Oils","name":"Avocado_Oil"},
  {"category":"Beverages","name":"Smoothie"},
  {"category":"Grains and Lentils","name":"Organic_Quinoa"},
  {"category":"Dairy","name":"Organic_Whipped_Cream"},
  {"category":"Office Supplies","name":"Binder"},
  {"category":"Office Supplies","name":"Staples"},
  {"category":"Produce","name":"Orange"},
  {"category":"Sweets","name":"3_Musketeers"},
  {"category":"Sweets","name":"Jawbreakers"},
  {"category":"Produce","name":"Watermelon"},
  {"category":"Meat","name":"Sausage"},
  {"category":"Bath","name":"Bath_Caddy"},
  {"category":"Dairy","name":"Organic_Cottage_Cheese"},
  {"category":"Bath","name":"Conditioner"},
  {"category":"Dairy","name":"Organic_Cheese"},
  {"category":"Grains and Lentils","name":"Barley"},
  {"category":"Oils","name":"Palm_Oil"},
  {"category":"Produce","name":"Organic_Tomato"},
  {"category":"Canned Goods","name":"Organic_Canned_Green_beans"},
  {"category":"Baby Care","name":"Baby_formula"},
  {"category":"Dairy","name":"Organic_Mozzarella_Cheese"},
  {"category":"Produce","name":"Organic_Kiwi"},
  {"category":"Frozen","name":"Frozen_Organic_hamburger_patties"},
  {"category":"Flour","name":"Self-Rising_Flour"},
  {"category":"Flour","name":"Bread_Flour"},
  {"category":"Spices","name":"Basil"},
  {"category":"Flour","name":"Barley_Flour"},
  {"category":"Grains and Lentils","name":"Organic_Split_Peas"},
  {"category":"Health Supplies","name":"Tweezers"},
  {"category":"Produce","name":"Organic_Grapes"},
  {"category":"Dairy","name":"Evaporated_Milk"},
  {"category":"Frozen","name":"Frozen_Organic_pasta"},
  {"category":"Canned Goods","name":"Canned_Beans"},
  {"category":"Health Supplies","name":"Pain_relievers_(e.g.,_acetaminophen,_ibuprofen)"},
  {"category":"Condiments","name":"Salsa"},
  {"category":"Canned Goods","name":"Organic_Canned_Sardines"},
  {"category":"Office Supplies","name":"Graph_Paper"},
  {"category":"Oils","name":"Pumpkin_Seed_Oil"},
  {"category":"Canned Goods","name":"Canned_Salmon"},
  {"category":"Frozen","name":"Frozen_Organic_ice_cream"},
  {"category":"Frozen","name":"Frozen_pizza"},
  {"category":"Condiments","name":"Mustard_Seed"},
  {"category":"Produce","name":"Pineapple"},
  {"category":"Flour","name":"Spelt_Flour"},
  {"category":"Health Supplies","name":"Alcohol_swabs"},
  {"category":"Baby Care","name":"Diaper_rash_cream"},
  {"category":"Office Supplies","name":"Manila_Folders"},
  {"category":"Office Supplies","name":"Notebook"},
  {"category":"Office Supplies","name":"Desk_Calendar"},
  {"category":"Office Supplies","name":"Receipts"},
  {"category":"Dairy","name":"Ice_Cream"},
  {"category":"Meat","name":"Salmon"},
  {"category":"Flour","name":"Soy_Flour"},
  {"category":"Baby Care","name":"Baby_soap"},
  {"category":"Grains and Lentils","name":"Organic_Lentils"},
  {"category":"Sweets","name":"Almond_Joy"},
  {"category":"Canned Goods","name":"Organic_Canned_Refried_beans"},
  {"category":"Frozen","name":"Frozen_hamburger_patties"},
  {"category":"Flour","name":"Tapioca_Flour"},
  {"category":"Office Supplies","name":"Catalogs"},
  {"category":"Oils","name":"Mustard_Oil"},
  {"category":"Dairy","name":"Organic_Cream"},
  {"category":"Sweets","name":"Lindt_Lindor"},
  {"category":"Bath","name":"Bar_Soap"},
  {"category":"Spices","name":"Caraway_seeds"},
  {"category":"Dairy","name":"Organic_Milk"},
  {"category":"Health Supplies","name":"Allergy_medication"},
  {"category":"Office Supplies","name":"Toilet_paper"},
  {"category":"Bath","name":"Shower_Cap"},
  {"category":"Oils","name":"Corn_Oil"},
  {"category":"Sweets","name":"Reeses_Peanut_Butter_Cups"},
  {"category":"Health Supplies","name":"Elastic_bandages"},
  {"category":"Oils","name":"Organic_Hazelnut_Oil"},
  {"category":"Oils","name":"Canola_Oil"},
  {"category":"Baby Care","name":"Breast_pump"},
  {"category":"Beverages","name":"Orange_Juice"},
  {"category":"Grains and Lentils","name":"Organic_Black_Beans"},
  {"category":"Health Supplies","name":"Antiseptic_wipes"},
  {"category":"Spices","name":"Cumin"},
  {"category":"Frozen","name":"Frozen_Organic_breakfast_items"},
  {"category":"Sweets","name":"Tootsie_Roll"},
  {"category":"Sweets","name":"Pop_Rocks"},
  {"category":"Office Supplies","name":"Graph_paper"},
  {"category":"Grains and Lentils","name":"Buckwheat"},
  {"category":"Beverages","name":"Iced_Tea"},
  {"category":"Spices","name":"Turmeric"},
  {"category":"Baby Care","name":"Baby_brush_and_comb_set"},
  {"category":"Canned Goods","name":"Canned_Coconut_milk"},
  {"category":"Baby Care","name":"Baby_oil"},
  {"category":"Office Supplies","name":"Envelopes"},
  {"category":"Sweets","name":"Junior_Mints"},
  {"category":"Grains and Lentils","name":"Bulgur"},
  {"category":"Condiments","name":"Ketchup"},
  {"category":"Office Supplies","name":"Brown_paper"},
  {"category":"Beverages","name":"Lime_Soda"},
  {"category":"Grains and Lentils","name":"Organic_Chickpeas"},
  {"category":"Health Supplies","name":"Multivitamins"},
  {"category":"Bath","name":"Body_Lotion"},
  {"category":"Spices","name":"Ginger"},
  {"category":"Sweets","name":"Swedish_Fish"},
  {"category":"Sweets","name":"Nestle_Crunch"},
  {"category":"Frozen","name":"Frozen_desserts"},
  {"category":"Baby Care","name":"Baby_towels"},
  {"category":"Produce","name":"Organic_Watermelon"},
  {"category":"Produce","name":"Banana"},
  {"category":"Office Supplies","name":"Printer_paper"},
  {"category":"Office Supplies","name":"Pen"},
  {"category":"Frozen","name":"Frozen_Organic_broccoli"},
  {"category":"Sweets","name":"Gummy_Bears"},
  {"category":"Office Supplies","name":"Newspaper"},
  {"category":"Oils","name":"Safflower_Oil"},
  {"category":"Baby Care","name":"Baby_nail_clippers"},
  {"category":"Oils","name":"Sunflower_Oil"},
  {"category":"Dairy","name":"Cheddar_Cheese"},
  {"category":"Frozen","name":"Frozen_French_fries"},
  {"category":"Sweets","name":"Cadbury_Dairy_Milk"},
  {"category":"Office Supplies","name":"Desk_Organizer"},
  {"category":"Canned Goods","name":"Organic_Canned_Artichoke_hearts"},
  {"category":"Spices","name":"Rosemary"},
  {"category":"Oils","name":"Grapeseed_Oil"},
  {"category":"Office Supplies","name":"Rubber_Bands"},
  {"category":"Dairy","name":"Sour_Cream"},
  {"category":"Baby Care","name":"Baby_first_aid_kit"},
  {"category":"Health Supplies","name":"Cough_drops"},
  {"category":"Beverages","name":"Instant_Coffee"},
  {"category":"Dairy","name":"Organic_Parmesan_Cheese"},
  {"category":"Office Supplies","name":"Cardstock"},
  {"category":"Health Supplies","name":"Ace_bandage"},
  {"category":"Flour","name":"Coconut_Flour"},
  {"category":"Bath","name":"Shampoo"},
  {"category":"Canned Goods","name":"Canned_Pumpkin"},
  {"category":"Canned Goods","name":"Organic_Canned_Peas"},
  {"category":"Dairy","name":"Cream"},
  {"category":"Baby Care","name":"Diapers"},
  {"category":"Frozen","name":"Frozen_Organic_shrimp"},
  {"category":"Baby Care","name":"Nursing_pads"},
  {"category":"Grains and Lentils","name":"Organic_Oats"},
  {"category":"Office Supplies","name":"Push_Pins"},
  {"category":"Office Supplies","name":"Sticky_notes"},
  {"category":"Office Supplies","name":"Drawing_Pins"},
  {"category":"Grains and Lentils","name":"Green_Lentils"},
  {"category":"Produce","name":"Organic_Onion"},
  {"category":"Oils","name":"Organic_Coconut_Oil"},
  {"category":"Canned Goods","name":"Organic_Canned_Pumpkin"},
  {"category":"Oils","name":"Sesame_Oil"},
  {"category":"Office Supplies","name":"Paper_clips"},
  {"category":"Produce","name":"Bell_Pepper"},
  {"category":"Flour","name":"Cake_Flour"},
  {"category":"Office Supplies","name":"Glue_Stick"},
  {"category":"Grains and Lentils","name":"Organic_Bulgur"},
  {"category":"Baby Care","name":"Baby_monitor"},
  {"category":"Bath","name":"Bath_Mat"},
  {"category":"Oils","name":"Peanut_Oil"},
  {"category":"Frozen","name":"Frozen_Organic_French_fries"},
  {"category":"Grains and Lentils","name":"Organic_Buckwheat"},
  {"category":"Produce","name":"Organic_Blueberry"},
  {"category":"Baby Care","name":"Bottle_warmer"},
  {"category":"Canned Goods","name":"Organic_Canned_Mushrooms"},
  {"category":"Sweets","name":"Snickers"},
  {"category":"Oils","name":"Walnut_Oil"},
  {"category":"Office Supplies","name":"Paper_plates"},
  {"category":"Beverages","name":"Lemonade"},
  {"category":"Oils","name":"Organic_Flaxseed_Oil"},
  {"category":"Frozen","name":"Frozen_Organic_desserts"},
  {"category":"Health Supplies","name":"Prescription_medications"},
  {"category":"Condiments","name":"Honey_Mustard"},
  {"category":"Office Supplies","name":"Binder_Clips"},
  {"category":"Meat","name":"Bacon"},
  {"category":"Bath","name":"Epsom_Salt"},
  {"category":"Oils","name":"Organic_Canola_Oil"},
  {"category":"Frozen","name":"Frozen_fruit"},
  {"category":"Frozen","name":"Frozen_vegetables"},
  {"category":"Bath","name":"Shower_Curtain"},
  {"category":"Flour","name":"Rice_Flour"},
  {"category":"Grains and Lentils","name":"Organic_Basmati_Rice"},
  {"category":"Grains and Lentils","name":"Chickpeas"},
  {"category":"Oils","name":"Organic_Jojoba_Oil"},
  {"category":"Oils","name":"Organic_Almond_Oil"},
  {"category":"Office Supplies","name":"Paper_towel"},
  {"category":"Sweets","name":"York_Peppermint_Pattie"},
  {"category":"Sweets","name":"Rolo"},
  {"category":"Frozen","name":"Frozen_breakfast_items"},
  {"category":"Sweets","name":"Hersheys_Kisses"},
  {"category":"Spices","name":"Fennel_seeds"},
  {"category":"Produce","name":"Organic_Strawberry"},
  {"category":"Frozen","name":"Frozen_broccoli"},
  {"category":"Produce","name":"Grapes"},
  {"category":"Health Supplies","name":"Gauze_pads"},
  {"category":"Canned Goods","name":"Canned_Tuna"},
  {"category":"Spices","name":"Garlic_powder"},
  {"category":"Oils","name":"Flaxseed_Oil"},
  {"category":"Bath","name":"Body_Wash"},
  {"category":"Canned Goods","name":"Organic_Canned_Chickpeas"},
  {"category":"Canned Goods","name":"Canned_Soup_(various_types)"},
  {"category":"Canned Goods","name":"Organic_Canned_Soup_(various_types)"},
  {"category":"Office Supplies","name":"File_folders"},
  {"category":"Health Supplies","name":"Hot_water_bottle"},
  {"category":"Baby Care","name":"Baby_shampoo_and_body_wash_combo"},
  {"category":"Sweets","name":"Toffee"},
  {"category":"Baby Care","name":"Baby_bibs"},
  {"category":"Spices","name":"Cardamom"},
  {"category":"Sweets","name":"Airheads"},
  {"category":"Sweets","name":"Reeses_Pieces"},
  {"category":"Bath","name":"Bath_Brush"},
  {"category":"Produce","name":"Kiwi"},
  {"category":"Frozen","name":"Frozen_Organic_garlic_bread"},
  {"category":"Bath","name":"Bath_Salts"},
  {"category":"Office Supplies","name":"Ink_Cartridges"},
  {"category":"Canned Goods","name":"Organic_Canned_Tuna"},
  {"category":"Beverages","name":"Apple_Juice"},
  {"category":"Flour","name":"Rye_Flour"},
  {"category":"Health Supplies","name":"Medical_mask"},
  {"category":"Office Supplies","name":"Paper_cups"},
  {"category":"Dairy","name":"Cream_Cheese"},
  {"category":"Oils","name":"Organic_Walnut_Oil"},
  {"category":"Spices","name":"Oregano"},
  {"category":"Office Supplies","name":"Dry_Erase_Markers"},
  {"category":"Bath","name":"Body_Scrub"},
  {"category":"Condiments","name":"Horseradish"},
  {"category":"Beverages","name":"Mango_Lassi"},
  {"category":"Produce","name":"Spinach"},
  {"category":"Office Supplies","name":"Copy_paper"},
  {"category":"Sweets","name":"Milky_Way"},
  {"category":"Sweets","name":"Caramel"},
  {"category":"Meat","name":"Ham"},
  {"category":"Dairy","name":"Organic_Sour_Cream"},
  {"category":"Canned Goods","name":"Organic_Canned_Salmon"},
  {"category":"Grains and Lentils","name":"Brown_Rice"},
  {"category":"Office Supplies","name":"Clipboard"},
  {"category":"Spices","name":"Celery_seeds"},
  {"category":"Oils","name":"Organic_Olive_Oil"},
  {"category":"Grains and Lentils","name":"Organic_Millet"},
  {"category":"Beverages","name":"Green_Tea"},
  {"category":"Canned Goods","name":"Canned_Peaches"},
  {"category":"Health Supplies","name":"Adhesive_tape"},
  {"category":"Office Supplies","name":"Colored_Pencils"},
  {"category":"Health Supplies","name":"Instant_cold_packs"},
  {"category":"Baby Care","name":"Baby_clothes"},
  {"category":"Office Supplies","name":"Index_cards"},
  {"category":"Produce","name":"Organic_Potato"},
  {"category":"Grains and Lentils","name":"Lentils"},
  {"category":"Flour","name":"Chickpea_Flour"},
  {"category":"Baby Care","name":"Baby_blankets"},
  {"category":"Condiments","name":"Hummus"},
  {"category":"Canned Goods","name":"Canned_Pineapple"},
  {"category":"Dairy","name":"Organic_Condensed_Milk"},
  {"category":"Office Supplies","name":"Kraft_paper"},
  {"category":"Office Supplies","name":"Markers"},
  {"category":"Canned Goods","name":"Organic_Canned_Peaches"},
  {"category":"Meat","name":"Crab"},
  {"category":"Oils","name":"Organic_Sunflower_Oil"},
  {"category":"Sweets","name":"Skittles"},
  {"category":"Baby Care","name":"Baby_bath_tub"},
  {"category":"Bath","name":"Shower_Gel"},
  {"category":"Bath","name":"Bath_Gloves"},
  {"category":"Canned Goods","name":"Canned_Green_beans"},
  {"category":"Frozen","name":"Frozen_ice_cream"},
  {"category":"Office Supplies","name":"Folders"},
  {"category":"Canned Goods","name":"Organic_Canned_Black_olives"},
  {"category":"Canned Goods","name":"Canned_Spaghetti_sauce"},
  {"category":"Frozen","name":"Frozen_Organic_vegetables"},
  {"category":"Office Supplies","name":"USB_Flash_Drive"},
  {"category":"Condiments","name":"Chutney"},
  {"category":"Canned Goods","name":"Canned_Peas"},
  {"category":"Spices","name":"Sage"},
  {"category":"Canned Goods","name":"Canned_Sardines"},
  {"category":"Sweets","name":"Hersheys_Special_Dark"},
  {"category":"Produce","name":"Apple"},
  {"category":"Beverages","name":"Whiskey"},
  {"category":"Produce","name":"Organic_Banana"},
  {"category":"Dairy","name":"Parmesan_Cheese"},
  {"category":"Oils","name":"Jojoba_Oil"},
  {"category":"Grains and Lentils","name":"Basmati_Rice"},
  {"category":"Produce","name":"Lettuce"},
  {"category":"Oils","name":"Hazelnut_Oil"},
  {"category":"Baby Care","name":"Baby_powder"},
  {"category":"Flour","name":"Pastry_Flour"},
  {"category":"Grains and Lentils","name":"Organic_Brown_Rice"},
  {"category":"Spices","name":"Saffron"},
  {"category":"Baby Care","name":"Baby_pacifiers"},
  {"category":"Oils","name":"Organic_Mustard_Oil"},
  {"category":"Grains and Lentils","name":"Amaranth"},
  {"category":"Canned Goods","name":"Canned_Mushrooms"},
  {"category":"Condiments","name":"Soy_Sauce"},
  {"category":"Office Supplies","name":"Whiteboard"},
  {"category":"Frozen","name":"Frozen_Organic_dumplings"},
  {"category":"Beverages","name":"Sprite"},
  {"category":"Health Supplies","name":"Hydrogen_peroxide"},
  {"category":"Office Supplies","name":"Legal_pads"},
  {"category":"Spices","name":"Mustard_seeds"},
  {"category":"Grains and Lentils","name":"Organic_Green_Lentils"},
  {"category":"Grains and Lentils","name":"Kidney_Beans"},
  {"category":"Produce","name":"Organic_Pineapple"},
  {"category":"Canned Goods","name":"Canned_Artichoke_hearts"},
  {"category":"Oils","name":"Organic_Macadamia_Nut_Oil"},
  {"category":"Spices","name":"Onion_powder"},
  {"category":"Baby Care","name":"Baby_socks"},
  {"category":"Frozen","name":"Frozen_Organic_yogurt"},
  {"category":"Grains and Lentils","name":"Black_Beans"},
  {"category":"Health Supplies","name":"Cold_and_flu_medicine"},
  {"category":"Sweets","name":"Haribo_Goldbears"},
  {"category":"Oils","name":"Olive_Oil"},
  {"category":"Frozen","name":"Frozen_spinach"},
  {"category":"Produce","name":"Broccoli"},
  {"category":"Grains and Lentils","name":"Wild_Rice"},
  {"category":"Grains and Lentils","name":"Farro"},
  {"category":"Spices","name":"Nutmeg"},
  {"category":"Flour","name":"Buckwheat_Flour"},
  {"category":"Produce","name":"Cucumber"},
  {"category":"Spices","name":"Paprika"},
  {"category":"Meat","name":"Lamb"},
  {"category":"Bath","name":"Face_Towel"},
  {"category":"Canned Goods","name":"Canned_Refried_beans"},
  {"category":"Bath","name":"Bubble_Bath"},
  {"category":"Produce","name":"Carrot"},
  {"category":"Beverages","name":"Ginger_Ale"},
  {"category":"Office Supplies","name":"Sketchbook"},
  {"category":"Sweets","name":"Kit_Kat"},
  {"category":"Frozen","name":"Frozen_yogurt"},
  {"category":"Bath","name":"Shower_Speaker"},
  {"category":"Oils","name":"Soybean_Oil"},
  {"category":"Office Supplies","name":"Crayons"},
  {"category":"Health Supplies","name":"Thermometer"},
  {"category":"Spices","name":"Cinnamon"},
  {"category":"Baby Care","name":"Baby_bottles"},
  {"category":"Grains and Lentils","name":"Organic_Farro"},
  {"category":"Baby Care","name":"Baby_shampoo"}]
  
